name = "SparseTN"
uuid = "fecd5469-1712-4901-ad7a-bda207dba756"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BitBasis = "0.9.10"
OMEinsum = "0.8.7"
SparseArrays = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
