name = "OMSparseEinsum"
uuid = "3e48f91b-32ac-4cc7-9c0f-e9f53eeef932"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BitBasis = "0.9.10"
OMEinsum = "0.8"
SparseArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
